/*
he sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include<stdio.h>


int getPrime(int FirstInputNumber)/*소인수 구하는 함수입니다*/
{
		int i,PrimeNumber,InputNumber;
		int Prime[600];/*소인수가 50개가 넘으면 []안의 숫자를 알맞게 올려주심 됩니다*/
		int X;
		int count_prime[600];
		int count_n=0, count=1;
		PrimeNumber=0;
		InputNumber=FirstInputNumber;
	

		for(i=2;i<=InputNumber;i++)
		{
			if(InputNumber%i==0)
			{
				Prime[PrimeNumber]=i;				
				if(PrimeNumber >0){
					if(Prime[PrimeNumber] == Prime[PrimeNumber-1]){
						count_prime[count_n-1]=count_prime[count_n-1]+1;
					}else{
						count_prime[count_n]=2;
						count_n= count_n+1;
					}
				}else{
					count_prime[count_n]=2;
					count_n= count_n+1;
				}
				PrimeNumber++;
				InputNumber=InputNumber/i;
				i=1;
			}
		}
		for(i=0 ; i<count_n ; i++){
			count = count_prime[i] * count;
		}
		return count;
		/*
		X=1;

		i=0;
		
		while(FirstInputNumber!=X)
		{
			printf("%d ",Prime[i]);
				X=X*Prime[i];
			i++;
		}*/
}


int main12(){
	int j, i, num=0;
	int triangle[100000];
	int tmp;
	triangle[0]=0;

	for(j=1 ; j<100000 ; j++){
		triangle[j]=triangle[j-1]+j;
	}

	for(j=1 ; j<100000 ; j++){
		num = getPrime(triangle[j]);
		//printf("%d\n", num);
		if(num > 500){
			printf("result is %dth triangle num %d -> %d \n", j, triangle[j], num);	
			return 0;
		}
	
	}
	
	return 0;
	
}