//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#include<stdio.h>

int main_problem2(){
	int i=0, j=1, sum=0, evensum=0;
	int cnt=0;
	
	while(sum < 4000000){
		sum = i+j;
		i = j;
		j = sum;
		if(sum%2==0){
			evensum = sum+evensum;
		}
		printf("%d ", sum);
	}
	printf("\n answer is %d ", evensum);
	
	return 0;
}